<?php

namespace Drupal\cdp_rest_api\Controller;

use Drupal\user\Controller\UserAuthenticationController;
use Symfony\Component\HttpFoundation\Request;

class LoginoController extends UserAuthenticationController{

  public function login(Request $request) {
    die("veikia");
    return parent::login($request); // TODO: Change the autogenerated stub
  }

}