<?php

use Drupal\cdp_register_form\Form\CdpDeveloperRegisterForm;
use Drupal\cdp_register_form\Form\CdpTechleadRegisterForm;
/**
 * @file
 * Primary module hooks for CDP User custom register and login form module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_entity_type_alter().
 */
function cdp_register_form_entity_type_alter(array &$entity_types) {

  $entity_types['user']->setFormClass('registration_developers', \Drupal\cdp_register_form\Form\MainRegisterForm::class);
  $entity_types['user']->setFormClass('registration_techlead', \Drupal\cdp_register_form\Form\MainRegisterForm::class);

}

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function cdp_register_form_form_user_login_form_alter(array &$form, FormStateInterface $form_state) {
        array_unshift($form['#validate'], 'mail_login_extra_validate');

        $form['name']['#title'] = t('Email login');
        $form['name']['#description'] = '';
}

/**
 * Custom validate function to enable email address login.
 */
function mail_login_extra_validate($form, FormStateInterface &$form_state) {
  $login_input = $form_state->getValue('name');
  if (filter_var($login_input, FILTER_VALIDATE_EMAIL)) {
    $user = user_load_by_mail($login_input);
    if ($user) {
      $form_state->setValue('name', $user->getAccountName());
    }
  }
}
