<?php

/**
 * @file
 * Provides a developer tasks entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\cdp_tasks\Form\TaskChangeTimeForm;
use Drupal\cdp_tasks\Form\TasksForm;

/**
 * Implements hook_theme().
 */
function cdp_tasks_theme() {
  return [
    'tasks' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for developer tasks templates.
 *
 * Default template: tasks.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the developer tasks information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_tasks(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function cdp_tasks_entity_type_alter(array &$entity_types) {

  $entity_types['tasks']->setFormClass('changedev',TaskChangeTimeForm::class);
  $entity_types['tasks']->setFormClass('changetech',TaskChangeTimeForm::class);


}
